
const ALERT = "ALERT";
const REFTCH_CHATS = "REFTCH_CHATS";

const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_ATTACHMENTS_ALERT = "NEW_ATTACHMENTS_ALERT";

const NEW_REQUEST = "NEW_MESSAGE_ALERT";

const NEW_MESSAGE = "NEW_MESSAGE";

const NEW_MESSAGE_ALERT = "NEW_ATTACHMENTS_ALERT";

export {ALERT, REFTCH_CHATS, NEW_ATTACHMENTS_ALERT, NEW_ATTACHMENTS, NEW_REQUEST, NEW_MESSAGE, NEW_MESSAGE_ALERT}